### ISSUE TITLE
Sign operations and messages with Massa wallet

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#624]
**Context**
Enable users of DApps on Massa ecosystem to understand the context of operations and messages they are requested to sign with their Massa wallet.

Needs:
- sign all 5 types of operations
- sign 2 types of messages: plaintext, and binary data

**User flow**
- User is interacting with a Dapp
- DApp sends a signature request to Massa wallet
- User sees main information provided for each type of signature request (operation types, messages)
- User is able to provide the password to sign
- User sees error messages for incorrect password

**How to**

- [x] Call SC operation : 
   - [x] #610 -> frontend(call SC no description)
   - [x] https://github.com/massalabs/station-massa-wallet/issues/634 -> frontend(call SC w/ description)
   - [x] #587 -> backend
- [x] Execute SC operation : 
  - [x] https://github.com/massalabs/station-massa-wallet/issues/635 -> frontend
  - [x] #597 -> backend
- [x] Roll Buy/Sell
   - [x] #628-> backend
   - [x] https://github.com/massalabs/station-massa-wallet/issues/637 -> frontend
- [x] Transaction 
   - [x] #645
  - [x] https://github.com/massalabs/station-massa-wallet/issues/638 -> frontend 
- [ ] Message plaintext
  - [x] https://github.com/massalabs/station-massa-wallet/issues/636 -> frontend 
  - [x] #667 
- [x] Message binary
  - [x] https://github.com/massalabs/station-massa-wallet/issues/636 -> frontend 
 

- [x] #676

Follow up issue: #675

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

IMPORTANT Note from FE -> as the Fees BE is not ready yet will most likely have to add this feature at a later date

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by longgamma-massa** [comment]
I see it as should-have or nice-to-have. It improves the ICO quest projects' UX. Users will know what they are signing. cc @gregLibert

**Comment by longgamma-massa** [comment]
**Q/A testing** 
---
_no. 1. Only operations:_

Tested cases given by @B-Naoufal:
- [ ] Call SC with description - done
- [ ] Execute SC without description - done
- [ ] Transaction - done
- [ ] Roll buy - done
- [ ] Roll sell - done

- [ ] Improvement @mazmassa - We should follow standard in showing values in the frontend: "," to separate thousands and . decimals. 
<img width="362" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/113043914/d888ecdb-e187-45b0-ab9a-53dc1496fa8e">

@B-Naoufal Do I need to test examples of Execute SC with description? Is the behavior the same as Call SC?

**Comment by longgamma-massa** [comment]
**Q/A 'Sign a message':**
@mazmassa @B-Naoufal 
- We have a flaw in the implementation of the 'Message' field in the wails popup: 

![Image](https://github.com/massalabs/station-massa-wallet/assets/113043914/19f9a513-a203-417f-aa72-cfb53b042c31)

The message should be displayed to users in the same way as the description is done - user clicks to expand/collapse.
It should be unrelated of the property 'DisplayData'. Our agreement was to allow the display of string messages (user chooses to see or not see the message), but not of binary format messages.
