### ISSUE TITLE
Implement Sign FE Meta Issue 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#639]
Front End Tasks 
- [ ] https://github.com/massalabs/station-massa-wallet/issues/638
- [ ] https://github.com/massalabs/station-massa-wallet/issues/637
- [ ] https://github.com/massalabs/station-massa-wallet/issues/636
- [x] https://github.com/massalabs/station-massa-wallet/issues/635
- [ ] https://github.com/massalabs/station-massa-wallet/issues/634
- [x] https://github.com/massalabs/station-massa-wallet/issues/610 
--> We are currently waiting on fees to be implemented 

- [ ] Refacto to add fees (might not be necessary)

**Comment by pivilartisant** [comment]
cc @Thykof  &  a meta issue to track ongoing tasks
@longgamma-massa -> if there is any modifications or details feel free to add the to the relavant issue

**Comment by pivilartisant** [comment]
redundant meta isssue
